---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.11
  - name: debian-9.9

suites:
  - name: default
    run_list:
      - recipe[zabbix-custom-checks::default]
    attributes:
