---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: debian-8.5

suites:
  - name: default
    run_list:
      - recipe[zabbix-custom-checks::default]
    attributes:
